[package]
name = "simple_rust_login_with_mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwhash = "1"
regex = "1.8.1"

[dependencies.mongodb]
version = "2.5.0"
features = ["tokio-sync"]